apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend
   labels:
      apps: guestbook
      tier: frontend
spec:
    selector:
       matchLabels:
           app: guestbook
           tier: fronend
    replicas: 3
    template:
      metadata:
        labels:
          app: guestbook
          tier: frontend
      spec:
         containers:
         - name: php-redis
           image: gcr.io/google-samples/gb-frontend:v4
           resources:
              request: 
                 cpu: 100M
                 memory: 100Mi
          env:
          - name: GET_HOSTS_FROM
            # value: dns
            value: env
          ports:
          - contianerPort: 80